import { Elder, Contact, Baseline, TimelineEntry, Ward } from '@/types/carenet';

export const SEED_WARD: Ward = {
  id: 'ward-4-pathanamthitta',
  name: 'Ward 4 - Kozhencherry',
  panchayat: 'Pathanamthitta Grama Panchayat'
};

export const SEED_AMMINI_CONTACTS: Contact[] = [
  {
    id: 'c-suma-neighbor',
    elder_id: 'elder-ammini-78',
    name: 'Suma Nextdoor',
    phone: '+91 94471 23456',
    relationship: 'neighbor',
    ladder_position: 1,
    response_window_minutes: 20,
    quiet_hours_start: '22:00',
    quiet_hours_end: '06:00',
    timezone: 'Asia/Kolkata',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString()
  },
  {
    id: 'c-reeja-asha',
    elder_id: 'elder-ammini-78',
    name: 'Reeja V. (ASHA Worker)',
    phone: '+91 98470 98765',
    relationship: 'asha',
    ladder_position: 2,
    response_window_minutes: 30,
    quiet_hours_start: '22:00',
    quiet_hours_end: '06:00',
    timezone: 'Asia/Kolkata',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString()
  },
  {
    id: 'c-unni-family',
    elder_id: 'elder-ammini-78',
    name: 'Unni (Son - Sharjah)',
    phone: '+971 50 123 4567',
    relationship: 'family',
    ladder_position: 3,
    response_window_minutes: 45,
    quiet_hours_start: '23:00',
    quiet_hours_end: '07:00',
    timezone: 'Asia/Dubai',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString()
  }
];

export const SEED_ELDERS: Elder[] = [
  {
    id: 'elder-ammini-78',
    full_name: 'Rehana Hidayathulla',
    age: 92,
    address: 'Lakshmi Nivas, Ward 4, Kozhencherry, Pathanamthitta',
    ward_id: 'ward-4-pathanamthitta',
    primary_language: 'ml',
    conditions_notes: 'Hypertension, Cardiac monitoring, Morning BP & Insulin, High Attention Priority',
    baseline_established_at: new Date(Date.now() - 21 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    contacts: SEED_AMMINI_CONTACTS,
    current_stage: 'critical',
    concern_score: 95,
    last_signal_at: new Date(Date.now() - 3600000).toISOString(),
    ward: { id: 'ward-4-pathanamthitta', name: 'Ward 4 - Kozhencherry', panchayat: 'Pathanamthitta Grama Panchayat' }
  },
  {
    id: 'elder-mathew-82',
    full_name: 'K.P. Mathew',
    age: 82,
    address: 'Bethany Cottage, Ward 4, Kozhencherry, Pathanamthitta',
    ward_id: 'ward-4-pathanamthitta',
    primary_language: 'ml',
    conditions_notes: 'Type 2 Diabetes, Routine morning walking group member',
    baseline_established_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'normal',
    concern_score: 5,
    last_signal_at: new Date(Date.now() - 7200000).toISOString(),
    ward: { id: 'ward-4-pathanamthitta', name: 'Ward 4 - Kozhencherry', panchayat: 'Pathanamthitta Grama Panchayat' }
  },
  {
    id: 'elder-devaki-76',
    full_name: 'Devaki Amma',
    age: 76,
    address: 'Vrindavan, Ward 4, Kozhencherry, Pathanamthitta',
    ward_id: 'ward-4-pathanamthitta',
    primary_language: 'ml',
    conditions_notes: 'Mild cognitive decline, lives alone with ambient motion sensor',
    baseline_established_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'soft_concern',
    concern_score: 35,
    last_signal_at: new Date(Date.now() - 18000000).toISOString(),
    ward: { id: 'ward-4-pathanamthitta', name: 'Ward 4 - Kozhencherry', panchayat: 'Pathanamthitta Grama Panchayat' }
  },
  {
    id: 'elder-varghese-79',
    full_name: 'Varghese Cherian',
    age: 79,
    address: 'Grace Villa, Ward 4, Kozhencherry, Pathanamthitta',
    ward_id: 'ward-4-pathanamthitta',
    primary_language: 'ml',
    conditions_notes: 'Post-cardiac rehab, monitored daily by local neighbor team',
    baseline_established_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'normal',
    concern_score: 0,
    last_signal_at: new Date(Date.now() - 4000000).toISOString(),
    ward: { id: 'ward-4-pathanamthitta', name: 'Ward 4 - Kozhencherry', panchayat: 'Pathanamthitta Grama Panchayat' }
  },
  {
    id: 'elder-mariamma-81',
    full_name: 'Mariamma Joseph',
    age: 81,
    address: 'St. Marys Enclave, Ward 15, Kakkanad, Ernakulam (Kochi)',
    ward_id: 'ward-15-ernakulam',
    primary_language: 'ml',
    conditions_notes: 'Hypertension, smartwatch pulse & door contact sensor connected',
    baseline_established_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'verify',
    concern_score: 48,
    last_signal_at: new Date(Date.now() - 14000000).toISOString(),
    ward: { id: 'ward-15-ernakulam', name: 'Ward 15 - Kakkanad', panchayat: 'Thrikkakara Municipality (Kochi)' }
  },
  {
    id: 'elder-thomas-84',
    full_name: 'K.O. Thomas',
    age: 84,
    address: 'Hill View Annex, Ward 15, Kakkanad, Ernakulam (Kochi)',
    ward_id: 'ward-15-ernakulam',
    primary_language: 'ml',
    conditions_notes: 'Mobility support, evening automated wellness check-in',
    baseline_established_at: new Date(Date.now() - 50 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 70 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'normal',
    concern_score: 0,
    last_signal_at: new Date(Date.now() - 2000000).toISOString(),
    ward: { id: 'ward-15-ernakulam', name: 'Ward 15 - Kakkanad', panchayat: 'Thrikkakara Municipality (Kochi)' }
  },
  {
    id: 'elder-radhakrishnan-80',
    full_name: 'Dr. N. Radhakrishnan',
    age: 80,
    address: 'Palms Villa, Ward 12, Kowdiar, Thiruvananthapuram',
    ward_id: 'ward-12-trivandrum',
    primary_language: 'ml',
    conditions_notes: 'Retired professor, telehealth monitoring & morning pillbox',
    baseline_established_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 65 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'normal',
    concern_score: 2,
    last_signal_at: new Date(Date.now() - 5400000).toISOString(),
    ward: { id: 'ward-12-trivandrum', name: 'Ward 12 - Kowdiar', panchayat: 'Thiruvananthapuram Corporation' }
  },
  {
    id: 'elder-bhavani-75',
    full_name: 'Bhavani Amma',
    age: 75,
    address: 'Kausthubham, Ward 12, Kowdiar, Thiruvananthapuram',
    ward_id: 'ward-12-trivandrum',
    primary_language: 'ml',
    conditions_notes: 'Mild hypertension, active ASHA volunteer visit circuit',
    baseline_established_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'normal',
    concern_score: 0,
    last_signal_at: new Date(Date.now() - 1200000).toISOString(),
    ward: { id: 'ward-12-trivandrum', name: 'Ward 12 - Kowdiar', panchayat: 'Thiruvananthapuram Corporation' }
  },
  {
    id: 'elder-menon-85',
    full_name: 'P.V. Menon',
    age: 85,
    address: 'Swaraj Heights, Ward 7, Swaraj Round, Thrissur',
    ward_id: 'ward-7-thrissur',
    primary_language: 'ml',
    conditions_notes: 'Cardiac history, daily BP monitoring by ASHA worker',
    baseline_established_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 100 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'local_escalation',
    concern_score: 72,
    last_signal_at: new Date(Date.now() - 21000000).toISOString(),
    ward: { id: 'ward-7-thrissur', name: 'Ward 7 - Swaraj Round', panchayat: 'Thrissur Corporation' }
  },
  {
    id: 'elder-aisha-77',
    full_name: 'Aisha Beevi',
    age: 77,
    address: 'Baitul Noor, Ward 9, Calicut Beach, Kozhikode',
    ward_id: 'ward-9-kozhikode',
    primary_language: 'ml',
    conditions_notes: 'Asthma, smart inhaler sensor & morning check call',
    baseline_established_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'normal',
    concern_score: 10,
    last_signal_at: new Date(Date.now() - 4800000).toISOString(),
    ward: { id: 'ward-9-kozhikode', name: 'Ward 9 - Calicut Beach', panchayat: 'Kozhikode Corporation' }
  },
  {
    id: 'elder-sebastian-83',
    full_name: 'Sebastian Varghese',
    age: 83,
    address: 'Pine Valley, Ward 6, Kalpetta, Wayanad',
    ward_id: 'ward-6-wayanad',
    primary_language: 'ml',
    conditions_notes: 'High elevation hill ward, neighbor buddy response ladder active',
    baseline_established_at: new Date(Date.now() - 35 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'normal',
    concern_score: 0,
    last_signal_at: new Date(Date.now() - 3000000).toISOString(),
    ward: { id: 'ward-6-wayanad', name: 'Ward 6 - Kalpetta', panchayat: 'Kalpetta Municipality (Wayanad)' }
  },
  {
    id: 'elder-rosamma-78',
    full_name: 'Rosamma Luke',
    age: 78,
    address: 'Lake View Cottage, Ward 8, Kumarakom, Kottayam',
    ward_id: 'ward-8-kottayam',
    primary_language: 'ml',
    conditions_notes: 'Arthritis, morning BP medication & smart kettle sensor',
    baseline_established_at: new Date(Date.now() - 22 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'normal',
    concern_score: 4,
    last_signal_at: new Date(Date.now() - 1800000).toISOString(),
    ward: { id: 'ward-8-kottayam', name: 'Ward 8 - Kumarakom', panchayat: 'Kumarakom Panchayat (Kottayam)' }
  },
  {
    id: 'elder-pillai-81',
    full_name: 'K.N. Pillai',
    age: 81,
    address: 'Backwater Retreat, Ward 10, Kuttanad, Alappuzha',
    ward_id: 'ward-10-alappuzha',
    primary_language: 'ml',
    conditions_notes: 'Hypertension, island ward boat access team connected',
    baseline_established_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 55 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'soft_concern',
    concern_score: 28,
    last_signal_at: new Date(Date.now() - 9800000).toISOString(),
    ward: { id: 'ward-10-alappuzha', name: 'Ward 10 - Kuttanad', panchayat: 'Kuttanad Panchayat (Alappuzha)' }
  },
  {
    id: 'elder-leelamani-74',
    full_name: 'Leelamani Amma',
    age: 74,
    address: 'Ashtamudi Shores, Ward 11, Ashtamudi, Kollam',
    ward_id: 'ward-11-kollam',
    primary_language: 'ml',
    conditions_notes: 'Diabetes, morning walking group & ASHA worker circuit',
    baseline_established_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'normal',
    concern_score: 0,
    last_signal_at: new Date(Date.now() - 2500000).toISOString(),
    ward: { id: 'ward-11-kollam', name: 'Ward 11 - Ashtamudi', panchayat: 'Kollam Corporation' }
  },
  {
    id: 'elder-shankaran-84',
    full_name: 'Shankaran Nair',
    age: 84,
    address: 'Payyambalam Breeze, Ward 14, Payyambalam, Kannur',
    ward_id: 'ward-14-kannur',
    primary_language: 'ml',
    conditions_notes: 'Mild cognitive decline, ambient door sensor active',
    baseline_established_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 80 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'verify',
    concern_score: 52,
    last_signal_at: new Date(Date.now() - 15000000).toISOString(),
    ward: { id: 'ward-14-kannur', name: 'Ward 14 - Payyambalam', panchayat: 'Kannur Corporation' }
  },
  {
    id: 'elder-rukmini-79',
    full_name: 'Rukmini Amma',
    age: 79,
    address: 'Coastal View, Ward 8, Thalassery, Kannur',
    ward_id: 'ward-14-kannur',
    primary_language: 'ml',
    conditions_notes: 'Hypertension, morning BP medication & ASHA check',
    baseline_established_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'normal',
    concern_score: 0,
    last_signal_at: new Date(Date.now() - 3600000).toISOString(),
    ward: { id: 'ward-14-kannur', name: 'Ward 14 - Payyambalam', panchayat: 'Kannur Corporation' }
  },
  {
    id: 'elder-krishnan-82',
    full_name: 'K.V. Krishnan',
    age: 82,
    address: 'Agro Gardens, Ward 2, Chittur, Palakkad',
    ward_id: 'ward-2-palakkad',
    primary_language: 'ml',
    conditions_notes: 'Diabetes, morning walking group member',
    baseline_established_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 55 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'normal',
    concern_score: 2,
    last_signal_at: new Date(Date.now() - 2800000).toISOString(),
    ward: { id: 'ward-2-palakkad', name: 'Ward 2 - Chittur', panchayat: 'Chittur-Thathamangalam Municipality (Palakkad)' }
  },
  {
    id: 'elder-moideen-78',
    full_name: 'Moideen Koya',
    age: 78,
    address: 'Green Meadows, Ward 4, Tirur, Malappuram',
    ward_id: 'ward-4-malappuram',
    primary_language: 'ml',
    conditions_notes: 'Asthma, smart inhaler sensor & daily phone check',
    baseline_established_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 42 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'normal',
    concern_score: 5,
    last_signal_at: new Date(Date.now() - 4200000).toISOString(),
    ward: { id: 'ward-4-malappuram', name: 'Ward 4 - Tirur', panchayat: 'Tirur Municipality (Malappuram)' }
  },
  {
    id: 'elder-joseph-81',
    full_name: 'Joseph Augustine',
    age: 81,
    address: 'Mist Valley Cottage, Ward 3, Munnar, Idukki',
    ward_id: 'ward-3-idukki',
    primary_language: 'ml',
    conditions_notes: 'High altitude tea estate ward, neighbor buddy response active',
    baseline_established_at: new Date(Date.now() - 50 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 70 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'soft_concern',
    concern_score: 32,
    last_signal_at: new Date(Date.now() - 11000000).toISOString(),
    ward: { id: 'ward-3-idukki', name: 'Ward 3 - Munnar', panchayat: 'Munnar Panchayat (Idukki)' }
  },
  {
    id: 'elder-govinda-83',
    full_name: 'Govinda Bhat',
    age: 83,
    address: 'Fort Side Residency, Ward 1, Bekal, Kasaragod',
    ward_id: 'ward-1-kasaragod',
    primary_language: 'ml',
    conditions_notes: 'Cardiac history, daily vital telemetry monitoring',
    baseline_established_at: new Date(Date.now() - 65 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    contacts: [],
    current_stage: 'normal',
    concern_score: 0,
    last_signal_at: new Date(Date.now() - 1900000).toISOString(),
    ward: { id: 'ward-1-kasaragod', name: 'Ward 1 - Bekal', panchayat: 'Udma Panchayat (Kasaragod)' }
  }
];

export const SEED_BASELINES: Baseline[] = [
  {
    id: 'b-ammini-pillbox',
    elder_id: 'elder-ammini-78',
    signal_type: 'sensor_pillbox',
    expected_time_start: '07:30',
    expected_time_end: '08:45',
    expected_frequency_per_day: 1.0,
    confidence: 0.95,
    updated_at: new Date().toISOString()
  },
  {
    id: 'b-ammini-call',
    elder_id: 'elder-ammini-78',
    signal_type: 'call_answered',
    expected_time_start: '08:00',
    expected_time_end: '09:30',
    expected_frequency_per_day: 1.0,
    confidence: 0.90,
    updated_at: new Date().toISOString()
  }
];

export const SEED_TIMELINE: TimelineEntry[] = [
  {
    id: 't-1',
    elder_id: 'elder-ammini-78',
    entry_type: 'signal',
    actor_name: 'Rehana Hidayathulla',
    note: 'Smart Pillbox opened for morning dose (Amlodipine 5mg)',
    visibility: 'all',
    occurred_at: new Date(Date.now() - 25 * 3600000).toISOString()
  },
  {
    id: 't-2',
    elder_id: 'elder-ammini-78',
    entry_type: 'note',
    actor_name: 'Suma Nextdoor (Neighbor)',
    note: 'Visited Rehana in afternoon. Shared homemade appam. She felt cheerful.',
    visibility: 'all',
    occurred_at: new Date(Date.now() - 20 * 3600000).toISOString()
  },
  {
    id: 't-3',
    elder_id: 'elder-ammini-78',
    entry_type: 'note',
    actor_name: 'Reeja V. (ASHA Worker)',
    note: 'Routine monthly BP checkup done. Blood pressure 128/82 mmHg (Normal). Next doctor visit on Thursday.',
    visibility: 'all',
    occurred_at: new Date(Date.now() - 48 * 3600000).toISOString()
  },
  {
    id: 't-4',
    elder_id: 'elder-ammini-78',
    entry_type: 'signal',
    actor_name: 'System Callback',
    note: 'Automated morning routine check answered via phone (Press 1 confirmed OK)',
    visibility: 'all',
    occurred_at: new Date(Date.now() - 3600000).toISOString()
  }
];

